### ISSUE TITLE
[Feature Request]Try to use another config in your github project

### ISSUE THREAD

**Issue by revan-zhang** [thomasyimgit/TIL#2]
Hey guy. I know you were in trouble now. 

you should try to config your local config in this project every time you push, you could just pushed as the github user.

```shell
git config --local user.name ${your github user name}
git config --local user.email ${your github email here}
```

Thanks.

**Comment by cyan33** [comment]
@loatheb Thanks dude:)

**Comment by revan-zhang** [comment]
@thomasyimgit  np
